---
title: "Assignment1"
author: "Sophia Leiker"
date: "2/13/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Why I am Taking this Course

I am taking this course because I am interested in more of the CS side of programming, the data structures and best practices used. I have been working in R with classmates but am just starting some work with The Nature Conservancy which includes large databases, GitHub repositories, and moving data across multiple platforms. For this I feel like I hope to get out of this class more best practices on how to manage data as aligned with their various workflows. Most of my work that I envision for programming in my career is focused on data wrangling for spatial data science with an emphasis on remote sensing. I also hope to begin to learn python due to python being prominent for ArcPro/spatial data analysis and thus I plan to use the lessons from this class to other coding platforms. I heard we may do some work on building these functions "outside" the traditional environment that I have built functions (within R scripts, therefore limiting usage) which I am excited to learn more about. Again, just working to understand bigger programming/computing principals that are more highlighted in CS classes than the environmental data science courses I have taken.


***

## My Data Science Background

I have a background in R based on Bren’s intro and Advanced Data Science class. I have also been working on data analysis in R within my group project to carry out time series assessments of spatial ET measurements across a landscape. Finally I took a MEDS course on Remote Sensing Analysis which dove into more spatial data and map creation in R. I have also used Java Script briefly for remote sensing analysis in Google Earth Engine, as well as basic Python in an intro class during my undergraduate class. I hope to incorporate coding into future jobs as a "tool in my toolbox", rather than having a majority of my days coding. Trying to take this class on from the perspective of a project manager who needs to know how these things work and what options teams doing environmental analysis would have at their disposal.




***

END CODE
